In [6]:
Data Science Homework #1



In [ ]:
1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [45]:
import numpy as np

a = np.array(range(1, 11))

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [46]:
a = np.zeros((3,3), dtype=int)

print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [47]:
b = np.random.randint(1, 11, (5, 5))
print(b)

[[ 2  9  1  1  9]
 [ 6  1 10  3  3]
 [ 1 10  6  4  8]
 [ 2  4  1  8  3]
 [ 2  9  2 10  7]]


In [ ]:
4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [48]:
b = np.random.randint(0, 2, (4, 4), dtype=int)
print(b)

[[0 0 1 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]]


In [ ]:
5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [17]:
a = np.random.randint (1, 11, 5, dtype = int)
b = np.random.randint (1, 11, 5, dtype = int)
print(a)
print(b)
print(f"Додавання - {a+b}")
print(f"Віднімання - {a-b}")
print(f"Множення - {a*b}")

[6 2 2 5 3]
[ 6  4 10  9  7]
Додавання - [12  6 12 14 10]
Віднімання - [ 0 -2 -8 -4 -4]
Множення - [36  8 20 45 21]


In [ ]:
6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [18]:
a = np.random.rand(7)
b = np.random.rand(7)
print(a)
print(b)
c = np.dot(a, b)
print(c)

[0.71255862 0.97265081 0.01427258 0.71441535 0.33889633 0.63172498
 0.22010147]
[0.7606871  0.00847749 0.90823519 0.48751075 0.65182998 0.26777931
 0.72556184]
1.4612907004796778


In [ ]:
7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [19]:
a = np.random.randint(1,11, (2,2))
b = np.random.randint(1,11, (2,3))
print(a)       
print(b)  
c = np.dot(a, b)
print(c)

[[6 7]
 [7 4]]
[[ 4  4  3]
 [ 3 10  2]]
[[45 94 32]
 [40 68 29]]


In [ ]:
8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [20]:
a = np.random.randint(1, 11, (3, 3))
print(a)
a_inv = np.linalg.inv(a)
print(a_inv)

[[8 5 5]
 [4 3 5]
 [2 2 8]]
[[ 1.16666667 -2.5         0.83333333]
 [-1.83333333  4.5        -1.66666667]
 [ 0.16666667 -0.5         0.33333333]]


In [ ]:
9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [22]:
a = np.random.randint(0,2, (4,4),dtype=int)
print(a)
b = a.T
print(b)

[[1 1 0 0]
 [0 1 1 0]
 [1 1 1 1]
 [1 1 0 0]]
[[1 0 1 1]
 [1 1 1 1]
 [0 1 1 0]
 [0 0 1 0]]


In [ ]:
10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [24]:
a = np.random.randint(1,11, (3,4),dtype=int)
b = np.random.randint(1,11, 4, dtype=int)
c=np.dot(a,b)
print(a)
print(b)
print(c)

[[10  1  5  7]
 [ 5  5  5  5]
 [ 8  3  6  3]]
[ 5  5 10  1]
[112 105 118]


In [ ]:
11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [25]:
a = np.random.randint(0,2, (2,3),dtype=int)
b = np.random.randint(0,2, 3, dtype=int)
c=np.dot(a,b)
print(a)
print(b)
print(c)

[[0 0 0]
 [1 0 0]]
[1 1 1]
[0 1]


In [ ]:
12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [26]:
a = np.random.randint(1,11, (2,2),dtype=int)
b = np.random.randint(1,11, (2,2),dtype=int)
c= a * b
print(a)
print(b)
print(c)

[[ 7  6]
 [10 10]]
[[9 8]
 [2 4]]
[[63 48]
 [20 40]]


In [ ]:
13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [27]:
a = np.random.randint(1,11, (2,2),dtype=int)
b = np.random.randint(1,11, (2,2),dtype=int)
c= np.dot(a,b)
print(a)
print(b)
print(c)

[[7 8]
 [2 3]]
[[9 6]
 [6 6]]
[[111  90]
 [ 36  30]]


In [ ]:
14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [29]:
a = np.random.randint(1,101, (5,5),dtype=int)
print(a)
print(a.sum())

[[49 42 29 45 12]
 [65 13 49 28 34]
 [84 74 54  9 13]
 [16 51 47 79 78]
 [56 95 76 21 21]]
1140


In [ ]:
15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [31]:
a = np.random.randint(1,11, (4,4),dtype=int)
b = np.random.randint(1,11, (4,4),dtype=int)
print(a)
print(b)
print(a-b)

[[ 6  4  3  7]
 [ 2  9  5  3]
 [ 8  9 10  3]
 [ 4 10 10  3]]
[[ 8  3  8  5]
 [10  1  7  2]
 [ 8  4  1  2]
 [ 8  3  3  3]]
[[-2  1 -5  2]
 [-8  8 -2  1]
 [ 0  5  9  1]
 [-4  7  7  0]]


In [ ]:
16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [33]:
a = np.random.rand(3, 3)
sum_vector = np.sum(a, axis=1)

print(a)
print(sum_vector)


[[0.80196193 0.39173208 0.48990517]
 [0.24174847 0.94521195 0.93055416]
 [0.8975832  0.11469087 0.6946421 ]]
[1.68359918 2.11751457 1.70691617]


In [ ]:
17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [42]:
a = np.random.randint((3, 4), dtype=int)
b = a ** 2
print(a)
print(b)

[0 2]
[0 4]


In [ ]:
18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [44]:
a = np.random.randint(1, 51, 4)
b = a **0.5
print(a)
print(b)


[15 46 41 42]
[3.87298335 6.78232998 6.40312424 6.4807407 ]
